const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Dictionary,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.left
	];
};
self.C3_JsPropNameTable = [
	{map: 0},
	{實體: 0},
	{Tilemap: 0},
	{facing: 0},
	{"8方向": 0},
	{視野跟隨: 0},
	{Sprite: 0},
	{鍵盤: 0},
	{Tree: 0},
	{BattleBackground: 0},
	{BallNum: 0},
	{PokeBall: 0},
	{BattleText: 0},
	{BattleSprite: 0},
	{BattleCharactor: 0},
	{Battle_text: 0},
	{Browser: 0},
	{textBox: 0},
	{DialogString: 0},
	{DialogIndex: 0},
	{isTyping: 0},
	{BattleCharName: 0}
];

self.InstanceType = {
	map: class extends self.ITilemapInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	鍵盤: class extends self.IInstance {},
	Tree: class extends self.ITilemapInstance {},
	BattleBackground: class extends self.ITiledBackgroundInstance {},
	PokeBall: class extends self.ISpriteInstance {},
	BattleText: class extends self.IDictionaryInstance {},
	BattleSprite: class extends self.ISpriteInstance {},
	BattleCharactor: class extends self.IDictionaryInstance {},
	Battle_text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	textBox: class extends self.ISpriteInstance {}
}